version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres 
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    # env_file:- 
    #   ./.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=3112
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=d18ce4e7f5e5d1e58cfae937fe355329c1033b10ffa6865720ca828de338c42a
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60

    postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=3112
        - POSTGRES_DB=fastapi
        
      volumes:
        - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db:
